installing_message = "Reminder: yuzu is an <b>experimental</b> emulator. Stuff will break!"
hide_advanced = false


[[packages]]
name = "yuzu"
description = "Archive of the latest mainline builds of yuzu."
icon = "thicc_logo_installer_shadow.png"
default = true
launch_after_install = true
    [packages.source]
    name = "github"
    match = "^yuzu-windows-msvc-[0-9]*-[0-9a-f]*.zip"
    allow_version_control = true
        [packages.source.config]
        repo = "yuzu-ssbu/yuzu-mainline-builds"
    [[packages.shortcuts]]
    name = "yuzu"
    relative_path = "yuzu-windows-msvc/yuzu.exe"
    description = "Launch yuzu"

[[packages]]
name = "yuzu SSBU Optimizer"
description = "Optimizes yuzu settings for SSBU and adds useful mods."
icon = "yuzu_ssbu.png"
default = true
    [packages.source]
    name = "github"
    match = "yuzu-ssbu-optimizer.zip"
        [packages.source.config]
        repo = "saad-script/yuzu-ssbu-optimizer"
    [[packages.shortcuts]]
    name = "yuzu SSBU Optimizer"
    relative_path = "yuzu-ssbu-optimizer.exe"
    description = "Optimize yuzu settings for SSBU."
